add controllers, change services and repositories
AlexOrk/jrCourse pull request #3
Opened 2020-11-12 14:33 UTC by AlexOrk

2020-11-13 10:02 UTC, spiriq reviewed
Сразу, из небольших замечаний - старайся делать коммиты меньше, не один коммит "add controllers, change services and repositories", а три отдельных под каждый слой.

2020-11-13 10:05 UTC, spiriq commented on src/main/java/jr_course/controller/ExerciseController.java
> +        return exerciseService.findAllByGrammar_Id(grammarId);
Опять же, мелочь, но лучше не использовать _ в именах методов и переменных

2020-11-13 10:27 UTC, spiriq requested changes
+ Обсудим на созвоне

2020-11-14 17:18 UTC, AlexOrk commented on src/main/java/jr_course/controller/ExerciseController.java
> +        return exerciseService.findAllByGrammar_Id(grammarId);
Исправил

2020-11-16 20:32 UTC, spiriq approved these changes
Есть некоторые вопросы, обсудим завтра голосом

2020-11-17 11:45 UTC, merged